---
kind: pipeline
type: docker
name: logger

steps:
- name: test 
  image: golang:1.22
  volumes:
  - name: deps
    path: /go/src/mod
  commands:
  - go test 

- name: golangci-lint
  image: golangci/golangci-lint:v1.57
  commands:
  - golangci-lint run

volumes:
- name: deps
  temp: {}
