kind: pipeline
name: default

steps:
- name: test 
  image: golang:1.17.8
  volumes:
  - name: deps
    path: /go/src/mod
  commands:
  - go test 

- name: golangci-lint
  image: golangci/golangci-lint:v1.44
  commands:
  - golangci-lint run

volumes:
- name: deps
  temp: {}
