run:
  timeout: 5m

linters-settings:
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 15
    govet:
      check-shadowing: true
    lll:
      line-length: 140
    fieldalignment:
      suggest-new: true
    misspell:
      locale: US  
    exhaustive:
      default-signifies-exhaustive: true
    varnamelen:
      min-name-length: 2
      ignore-names:
        - err
        - n
        - i
        - w
    tagliatelle:
      case:
        use-field-name: true
        rules:
          json: snake
          yaml: camel
          xml: camel
          bson: camel
          avro: snake

linters:
    enable-all: true
    disable:
    # deprecated
      - interfacer
      - structcheck
      - varcheck
      - golint
      - deadcode
      - scopelint
      - exhaustivestruct
      - ifshort
      - nosnakecase
      - maligned

      - depguard # need configure
      - nolintlint # use with space

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - ireturn
        - exhaustruct
        - gochecknoglobals
    - path: _example_test\.go
      linters:
        - lll
        - goerr113
    - path: example/*
      linters:
        - gomnd
        - lll
