version: "2"
linters:
  default: all
  disable:
    - wsl
    - noinlineerr
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - gitoa.ru

    funcorder:
      constructor: false
    recvcheck:
      disable-builtin: false
      exclusions:
        - "*.String"
        - "*.UnmarshalText" 
        - "*.UnmarshalJSON"
        - "*.UnmarshalBinary"
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          json: snake
          xml: camel
          yaml: camel
        use-field-name: true
    varnamelen:
      min-name-length: 2
      ignore-names:
        - err
        - "n"
        - i
        - w
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - exhaustruct
          - gochecknoglobals
          - ireturn
          - mnd
        path: _test\.go
      - linters:
          - err113
          - lll
        path: _example_test\.go
      - linters:
          - lll
          - mnd
        path: example/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
