// Code generated by "stringer -type=Level -linecomment"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelEmergency-0]
	_ = x[LevelAlert-1]
	_ = x[LevelCritical-2]
	_ = x[LevelError-3]
	_ = x[LevelWarning-4]
	_ = x[LevelNotice-5]
	_ = x[LevelInfo-6]
	_ = x[LevelDebug-7]
}

const _Level_name = "emergencyalertcriticalerrorwarningnoticeinfodebug"

var _Level_index = [...]uint8{0, 9, 14, 22, 27, 34, 40, 44, 49}

func (i Level) String() string {
	if i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
