// Code generated by "stringer -type=Level -linecomment -output=level_string.go"; DO NOT EDIT.

package otel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[levelDebug-5]
	_ = x[levelInfo-9]
	_ = x[levelInfo2-10]
	_ = x[levelWarn-13]
	_ = x[levelError-17]
	_ = x[levelError2-18]
	_ = x[levelError3-19]
	_ = x[levelFatal-21]
}

const (
	_Level_name_0 = "DEBUG"
	_Level_name_1 = "INFOINFO2"
	_Level_name_2 = "WARN"
	_Level_name_3 = "ERRORERROR2ERROR3"
	_Level_name_4 = "FATAL"
)

var (
	_Level_index_1 = [...]uint8{0, 4, 9}
	_Level_index_3 = [...]uint8{0, 5, 11, 17}
)

func (i Level) String() string {
	switch {
	case i == 5:
		return _Level_name_0
	case 9 <= i && i <= 10:
		i -= 9
		return _Level_name_1[_Level_index_1[i]:_Level_index_1[i+1]]
	case i == 13:
		return _Level_name_2
	case 17 <= i && i <= 19:
		i -= 17
		return _Level_name_3[_Level_index_3[i]:_Level_index_3[i+1]]
	case i == 21:
		return _Level_name_4
	default:
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
